# @format

# Change these first
owner: iamvikshan # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Vikshan
    url: https://vikshan.me
  - name: Amina Docs
    url: https://docs.vikshan.me
  - name: utopia
    check: 'tcp-ping'
    url: utopia.pylex.xyz
    port: 10957
  - name: Short Url Service
    url: https://go.vikshan.me
  - name: ViKSHaN Server Website
    url: https://server.vikshan.me
  - name: Vix Pix
    url: https://pixels.vikshan.me/

status-website:
  # theme
  theme: night
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.vikshan.me
  # baseUrl: /upptime
  logoUrl: https://github.com/iamvikshan/upptime/blob/master/assets/tmpng.png
  name: Vikshan Status Page
  customHeadHtml:
    '<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4999609620951427"
    crossorigin="anonymous"></script>'
  customBodyHtml: |
    <!--Start of Tawk.to Script-->
    <script type='text/javascript'>
    var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
    (function(){
    var s1=document.createElement('script'),s0=document.getElementsByTagName('script')[0];
    s1.async=true;
    s1.src='https://embed.tawk.to/656f9fb5ff45ca7d47872dab/1hgu0fng3';
    s1.charset='UTF-8';
    s1.setAttribute('crossorigin','*');
    s0.parentNode.insertBefore(s1,s0);
    })();
    </script>
    <!--End of Tawk.to Script-->
  # introTitle: "**Vikshan Status Page** is an open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is page uses **real-time** data from our [GitHub repository](https://github.com/iamvikshan/upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/iamvikshan/upptime
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
